### ISSUE TITLE
Fix REDME

### ISSUE THREAD

**Issue by zdenda142** [Bach174/Bach-towing#1]
Put these lines in your qb-core\shared/items.lua

-- Ropes  
	["tow_rope"] 		 	 		 = {["name"] = "tow_rope", 					["label"] = "Rope", 			["weight"] = 100, 		["type"] = "item", 			["image"] = "tow_rope.png", 			["unique"] = true, 	["useable"] = true, 	["shouldClose"] = false,    ["combinable"] = nil,   ["description"] = "Towing rope for cars"},

**Comment by Bach174** [comment]
Done :D
